Catalog/urls.py
from django.urls import path
from . import views

app_name = 'Catalog'

urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'), 
    path('books/<int:pk>/', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('authors/<int:pk>/', views.AuthorDetailView.as_view(), name='author-detail'),
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path('borrowed/', views.AllBookUsersBorrowed.as_view(), name='all-borrowed'),
    path('books/<uuid:pk>/renew/', views.renew_book_librairian, name='renew-book-librarian'),
]

LibralLocal/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include('Catalog.urls', namespace='Catalog')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalog/'))
]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


class Genre(models.Model):
    name = models.CharField(max_length=255, help_text="Saisir les genre litteraire disponible(ex: Science fiction)")

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=200, help_text='Saisir La Langue ex: French, English, Spanish etc..')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.ForeignKey('Author', on_delete=models.CASCADE, null=True)
    summary = models.TextField(max_length=1000, help_text="Entrer une breve description du livre")
    isbn = models.CharField('ISBN', max_length=13, help_text="Saisir le numero ISBN du livre")
    genre = models.ManyToManyField('Genre', help_text="Saisir le genre litteraire du livre")
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("Catalog:book-detail", args=[str(self.id)])

    def display_genre(self):
        return ' , '.join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = 'Genre'


class BookInstance(models.Model):
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID pour ce livre particulier')
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Livres disponibles'
    )

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set book as returned'),)

    def __str__(self):
        return f'{self.id} ({self.book.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Author(models.Model):
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', blank=True, null=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse("Catalog:author-detail", args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}'

Catalog/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks(default 3 weeks)")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Verifier si la date entree n'est pas passé
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Verifier si la date entree est dans l'intervalle (4 semaines a compter d'aujourd'hui)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Renvoyer toujours des données Effacer
        return data

Catalog/views.py
import datetime
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import reverse
from .forms import RenewBookForm
from .models import( 
    Book, BookInstance,
     Author, Genre)


def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.all().count()
    num_titles = Book.objects.filter(title__exact='Horreur').count()
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_titles': num_titles,
        'num_visits': num_visits,
    }

    return render(request, 'index.html', context=context)


class BookListView(ListView):
    model = Book
    paginate_by = 3
    template_name = 'catalog/book_list.html'

class BookDetailView(DetailView):  
    model = Book                                          
    template_name = "catalog/book_detail.html"

class AuthorListView(ListView):
    model = Author
    template_name = "catalog/author_list.html"

class AuthorDetailView(DetailView):
    model = Author
    template_name = "catalog/author.detail.html"

class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    models = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 3

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')
        

class AllBookUsersBorrowed(LoginRequiredMixin, ListView):
    models = BookInstance
    template_name = "catalog/bookinstance_user_borrowed.html"
    paginate_by = 3

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='o')
        

class MyView(PermissionRequiredMixin, View):
    permission_required = 'Catalog.can_mark_returned'
    

@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librairian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # Si la request est "POST" traité les données
    if request.method == 'POST':

        # Créez une instance de formulaire et remplissez-la avec les données de la requête (liaison):
        form = RenewBookForm(request.POST)

        # Verifier si le formulaire est valide:
        if form.is_valid():
            # On efface les donnees apres une soumission
            book_instance.due_back = form.cleaned_data['renewal_date']
            # Sauvegarde les données du formulaire
            book_instance.save()

            #Redirige l'utilisateur vers un nouvel url
            return HttpResponseRedirect(reverse('Catalog:all-borrowed'))
    
    # Si c'est la methode GET ou un autre methode creer un formulaire vide
    else:
        proposed_renewal_date = datetime.date.today() - datetime.timedelta(weeks=4)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
    
    context = {
        'form': form,
        'book_instance': book_instance,
    }
    return render(request, 'catalog/book_renew_librarian.html', context=context)

Catalog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Bibliothèque locale</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 sidebar">
          {% block sidebar %}
           <ul class="sidebar-nav">
              <li><a href="{% url 'Catalog:index' %}">Home</a></li>
              <li><a href="{% url 'Catalog:books' %}">Tous les livres</a></li>
              <li><a href="{% url 'Catalog:authors' %}">Tous les auteurs</a></li>

              {% if user.is_authenticated %}
              <li>User:{{ user.get_username }}</li>
              <li><a href="{% url 'Catalog:my-borrowed' %}">My Borrowed</a></li>
              <li><a href="{% url 'logout' %}?next={{request.path}}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'login' %}?next={{request.path }}">Login</a></li>
              {% endif %}
              <hr>
              {% if user.is_staff %}
              <li>Staff:{{ user.get_username }}</li>
              <li><a href="{% url 'Catalog:all-borrowed' %}?next={{request.path}}">All Borrowed</a></li>
              {% endif %}
           </ul>
          {% endblock %}
        </div>
        <div class="col-sm-8 ">
            {% block content %}
            {% endblock %}
            {% block pagination %}
              {% if is_paginated %}
                  <div class="pagination">
                      <span class="page-links">
                          {% if page_obj.has_previous %}
                              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">precedent</a>
                          {% endif %}
                          <span class="page-current">
                              Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
                          </span>
                          {% if page_obj.has_next %}
                              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">suivant</a>
                          {% endif %}
                      </span>
                  </div>
              {% endif %}
            {% endblock %} 
        </div>
    </div>
  </div>
</body>
</html>

Catalog/templates/index.html
{% extends 'base.html' %}


{% block content %}
<h1>Accueil de la Librairie Locale</h1>
<p>Bienvenue à la Librairie Locale, un site developpé par <em>Dino Petit Russe</em><p>
<h2>contenu dynamique</h2>
<p>La libraire dispose des livres et consorts:<p>
<ul>
    <li><strong>Livre: </strong>{{num_books}}</li>
    <li><strong>copies: </strong>{{num_books}}</li>
    <li><strong>copies disponibles: </strong>{{num_books}}</li>
    <li><strong>Author: </strong>{{num_authors}}</li>
    <li><strong>Genre: </strong>{{num_genres}}</li>
    <li><strong>Titles: </strong>{{num_titles}}</li>
</ul>
<p>Vous avez visité cette page {{ num_visits }} foi{{ num_visits|pluralize}}.</p>
<hr>
{% endblock %} 